name: Build Flet Windows App

on:
  workflow_dispatch:   # 仅手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet pyinstaller

      # 4. 安装 Flutter（flet build 需要）
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'   # 建议和本地一致
          channel: stable

      # 5. 打包 Windows 应用
      - name: Build Windows app
        run: flet build windows

      # 6. 上传打包结果（可下载）
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/**
